name: Jvav CI (Really)

on:
  push:
  pull_request:
    branches:
      - main
jobs:
  Build:
    strategy:
      matrix:
        jdkversion: [ 11 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdkversion }}
          cache: 'maven'
      - name: Build
        run: mvn -V -B clean package --file pom.xml
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Download
          path: ./target/ClientBoomer-PacketEvents-1.2.jar